[[headers]]
  # Ustaw nagłówek zezwalający na dostęp do wszystkich zasobów (CORS)
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/index.html"
  to = "/login.php"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/register.php"
  status = 200
